# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields:
  base_url: "https://benjaminnussbaum.at/trmnl/examples/uptime-kuma"
  #base_url: "http://localhost:3001"
  status_page_slug: "default"
  display_incident: true

# override variables
variables:
  trmnl: {}
